# Site settings
title: Hyperlink
email: hi@hyperlinkapp.com
description: "Connect the disconnected"
baseurl: ""
url: "http://hyperlinkapp.com"
twitter_username: hyperlinkapp
github_username: hyperlinkapp

# Build settings
markdown: kramdown
permalink: pretty
